<?php include __DIR__ . '/../header.html'; ?>
    <div class="container">
        <div class="row">
            <h3>Lista de Posts</h3>
            <a class="btn btn-primary" href="/posts/create">Cadastrar</a>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th class="">Opções</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($posts as $post) { ?>
                    <tr>
                        <td><?= $post->getId() ?></td>
                        <td><?= $post->getTitle() ?></td>
                        <td>
                            <?= "<a href='/posts/categories/{$post->getId()}'>Categorias</a>" ?> |
                            <?= "<a href='/posts/edit/{$post->getId()}'>Editar</a>" ?> |
                            <?= "<a href='/posts/remove/{$post->getId()}/submit'>Excluir</a>" ?>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html'; ?>