<?php include __DIR__ . '/../header.html'; ?>
<div class="container">
    <div class="row">
        <h3>Lista de categorias</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category){ ?>
                <tr>
                    <td><?= $category->getId() ?></td>
                    <td><?= $category->getName() ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<?php include __DIR__ . '/../footer.html'; ?>