<?php include __DIR__ . '/../header.html'; ?>
<div class="container">
    <div class="row">
        <h3>Lista de categorias</h3>
        <a class="btn btn-primary" href="/create">Cadastrar</a>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category){ ?>
                <tr>
                    <td><?= $category->getId() ?></td>
                    <td><?= $category->getName() ?></td>
                    <td><?= "<a href='/edit/{$category->getId()}'>Editar</a>" ?></td>
                    <td><?= "<a href='/remove/{$category->getId()}'>Excluir</a>" ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
<?php include __DIR__ . '/../footer.html'; ?>