<?php include __DIR__ . '/header.html'; ?>
    <div class="container">
        <div class="row">
            <h2>Noticias:</h2>
            <div class="col-md-10">
                <ul class="list-unstyled">
                    <?php foreach ($posts as $post): ?>
                        <li>
                            <div class="jumbotron">
                                <h2><?= $post->getTitle(); ?></h2>
                                <p class="text-justify">
                                    <?= substr($post->getContent(), 0, 200).' ...'; ?>
                                </p>
                                <p>
                                    <a class="btn btn-primary" href="/post/<?= $post->getId()?>" role="link">Leia Mais</a>
                                </p>
                            </div>
                        </li>
                    <?php endforeach; ?>

                </ul>
            </div>
            <div class="col-md-2">
                <ul>
                    <?php foreach ($categories as $category): ?>
                        <li class="list-group-item">
                           <a href="/<?= $category->getId(); ?>"> <?= $category->getName(); ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php include __DIR__ . '/footer.html'; ?>